### ISSUE TITLE
[BUG??] FIRAnalyticsVersionMismatch

### ISSUE THREAD

**Issue by ikicapitan** [Poing-Studios/godot-admob-ios#15]
Hi, its me again. All is working perfect, i only have a incompatibility between your plugin and other plugin.

**Describe the bug**
I added your plugin which is working incredibly good in iOS & Android. My problem now is that i've also a Firebase plugin. Using both plugins, give me a crash only on iOS, and it's because both uses FIRAnalytics but with different versions.

**To Reproduce**
1. Add your plugin.
2. Add Firebase Plugin.
3. Compile on iOS.

I'm just wondering if there's some file where i can change the number of version or something like that. I open many files on both plugins, but i dont found anything. I find GoogleAppMeasurement folders, but i cant change version, or maybe i dont know where or with which software. 

Here it's the exact line of error:

*** Terminating app due to uncaught exception 'FIRAnalyticsVersionMismatch', reason: 'Google Analytics for Firebase version (70100000) does not match with Google App Measurement (80901000) version. Please update.'

Thank you!

**Comment by gumaciel** [comment]
Hi, hmmm, instead of using the https://github.com/Poing-Studios/godot-admob-ios/releases/tag/v2.0.4 "googlemobileadssdkios.zip" that we provide, try to use Cocoapods

This should work: https://cocoapods.org/pods/Google-Mobile-Ads-SDK

I never tried to use the Firebase Plugin, can you give me details which plugin is it? The link of repository

A sample project would be great

**Comment by ikicapitan** [comment]
Thank you gumaciel.

I have chosen to download from windows the latest version of Admob SDK, as you said. 

I see that your plugin allows you to insert the SDK manually, which makes it dynamic. The other plugin (Firebase) doesn't seem to allow dynamically configuring the SDK, as apparently a part of it has files packed by the programmer.

I see that your plugin works correctly, so there is not much I can tell you. It's something related to another plugin so I'm going to put my focus on seeing what I can do there, although I don't think much more than what the plugin itself allows me.

I leave you the Firebase plugin, in case someone asks about this at least you know where the problem can come from. I appreciate the help provided. The topic can be closed.

https://github.com/DrMoriarty/godot-firebase-analytics
