### ISSUE TITLE
App Tracking Transparency permission request in admob

### ISSUE THREAD

**Issue by mani144** [Poing-Studios/godot-admob-ios#16]
Greetings,

i have been using ur admob plugin for a while. fantastic job btw

just a quick question, I'm always getting this msg from apple when i submit my application, is there something that I'm missing?

i remember that sometimes i see the popup for tacking the user and sometimes i don't. 

We're looking forward to completing our review, but we need more information to continue. Your app uses the AppTrackingTransparency framework, but we are unable to locate the App Tracking Transparency permission request when reviewed on iOS 15.2.1.

thank you for your work

**Comment by gumaciel** [comment]
Hello, thank you for using our plugin!

What message did Apple send to you?

To remove the AppTrackingTransparency, you need to remove this on your ".plist": https://developers.google.com/admob/ios/ios14#request

![image](https://user-images.githubusercontent.com/20030153/151474198-d6d16190-e7ed-48e9-986d-414c7b4914b2.png)

Or remove these line and export again:

https://github.com/Poing-Studios/godot-admob-ios/blob/master/plugin/admob/config/admob.gdip#L35-L36

**Comment by gumaciel** [comment]
`i remember that sometimes i see the popup for tacking the user and sometimes i don't.`

As I know, this popup will only display on the very first time of launching the app, to appear again you probably will need to uninstall and install again the app altogether.

**Comment by gumaciel** [comment]
Also: We don't use more the AppTrackingTransparency framework on our code

commit reference: https://github.com/Poing-Studios/godot-admob-ios/commit/7c51d5adef36c40ffddf058563d12019d75d0bda

Now need to use the UMP: https://support.google.com/fundingchoices/answer/9995402

**Comment by gumaciel** [comment]
Maybe this issue helps you: https://github.com/Poing-Studios/godot-admob-ios/issues/9

**Comment by mani144** [comment]
<img width="1214" alt="Screen Shot 2022-01-28 at 12 07 30 PM" src="https://user-images.githubusercontent.com/17520497/151518689-48000ddd-aebc-48a2-a746-018cc70452e8.png">

this is what I got from them, i will try to remove the permission and submit it later , thank you for your time :)

**Comment by mani144** [comment]
> Also: We don't use more the AppTrackingTransparency framework on our code
> 
> commit reference: [7c51d5a](https://github.com/Poing-Studios/godot-admob-ios/commit/7c51d5adef36c40ffddf058563d12019d75d0bda)
> 
> Now need to use the UMP: https://support.google.com/fundingchoices/answer/9995402
> 
> Please certify if you are using the latest version of our Plugin.
> 
> Editor: v1.2.3 iOS: v2.0.4 Android: v2.0.0
> 
> https://github.com/Poing-Studios/godot-admob-editor/releases/tag/v1.2.3

i already updated everything to the latest version.

**Comment by mani144** [comment]
<img width="766" alt="Screen Shot 2022-01-28 at 12 15 22 PM" src="https://user-images.githubusercontent.com/17520497/151519968-bd424d91-12a1-41fd-98f4-2399a1a9eef5.png">

i think im facing this problem because of this line below in admob.gdip.

**Comment by gumaciel** [comment]
Hi, as i understand you are collecting data on your app, so you need to use IDFA.

To enable follow this tutorial:

https://support.google.com/fundingchoices/answer/9995402
https://developers.google.com/admob/ump/ios/quick-start#app_tracking_transparency

I think you will need to to link the `AppTrackingTransparency` framework:

![image](https://user-images.githubusercontent.com/20030153/151529708-93f1fe6f-dbb9-4f91-9ca6-56f5754b85d3.png)

**Comment by mani144** [comment]
thanks for the information, i found out that they are asking because i used device id

**Comment by restcristian** [comment]
Hi @mani144 @gumaciel 

I actually got the same rejection message from Apple. As far as I understood from this thread, I would have to remove this line from` admob.gdip.` 

`NSUserTrackingUsageDescription="This identifier will be used to deliver personalized ads to you."`

Also, this is my privacy configuration. Since I am not tracking user data (besides of whatever Admob does) which options should I remove from there? or is it fine just as it is?

<img width="1169" alt="image" src="https://github.com/Poing-Studios/godot-admob-ios/assets/9398934/84a398ed-0e67-4ce5-82d5-8185aed4ad4d">

Thanks in advance. I would appreciate the support!

**Comment by gumaciel** [comment]
Hi, you need to keep this in the .gdip.

As I'm seen your account is fine

**Comment by restcristian** [comment]
Thanks @gumaciel. What would I need to do then to fix this?

**Comment by gumaciel** [comment]
Don't remove `NSUserTrackingUsageDescription="This identifier will be used to deliver personalized ads to you."` from `.gdip`

Also link `AppTrackingTransparency` framework like this comment: https://github.com/Poing-Studios/godot-admob-ios/issues/16#issuecomment-1024075010

**Comment by restcristian** [comment]
Cool. What if I am not collecting personal info? And don’t want to show personalized ads? Is it the same process?

**Comment by gumaciel** [comment]
If you are not collecting, I think you can ignore this.

If you still having problems with this, I recommend opening a conversation in the `Google Mobile Ads SDK Developers` group: https://groups.google.com/g/google-admob-ads-sdk
