### ISSUE TITLE
[BUG] Cant export to IOS (from PC) when the plugin is Active.

### ISSUE THREAD

**Issue by GogetaX** [Poing-Studios/godot-admob-ios#18]
**Describe the bug**
Ok, so i followed the tutorial for creating a custom build for ios,
that involved me to download iOS Template and GoogleMobileAdsSdkiOS
also installed both of the files where it should be res://ios/plugins/admob/lib/
so far, so good.
but for some reason, i get this error:
![image](https://user-images.githubusercontent.com/51264046/160212126-d8f3e986-03bf-47de-99fa-8f2ccc9c2755.png)
and the godot console gives me this:
![image](https://user-images.githubusercontent.com/51264046/160212143-af763999-11c8-41a7-b3ee-a512d2454b65.png)

**To Reproduce**
Export the project on PC, for iOS build, enable/disable the plugin to see the issue.

**Expected behavior**
when i disable the AdMob Plugin, i can export normally to ios

Versions:
Godot 3.4.2

**Comment by gumaciel** [comment]
Hi thank you for opening this bug, i will check it out!

If you are trying to export on a Windows OS maybe this is not really a bug of us but of Godot or even it's not even a bug at all because it doesn't make much sense to export to iOS if you're not on a Mac.

**Comment by GogetaX** [comment]
> Hi thank you for opening this bug, i will check it out!
> 
> If you are trying to export on a Windows OS maybe this is not really a bug of us but of Godot or even it's not even a bug at all because it doesn't make much sense to export to iOS if you're not on a Mac.

you are correct, godot cannot export directly to ios, but godot creates xcode project files including .apk file that i can run on external mac machine (Xcode)  and it does work flawlessly!
when i Enable the admob plugin, it does not want to compile.
my steps to make a work around are: github backup -> restore github on Linux -> run godot same version on linux -> Compile and sent back to my PC -> send to External Mac OS -> run xcode -> Push to iPhone.

half of those steps shouldnt be there.. 
please help me to fix this. tell me if you able to reproduce the bug.

thank you.

**Comment by GogetaX** [comment]
ok, so for some reason, i created a new project and included all the ios libraries including the admob plugin in order to sent you the project,
but in this case, it was working perfectly.
for some reason, new projects working, but this specific project cannot be exported.
i've searched all the export settings and even reset all the export settings in order to find the problem,
and i got nothing.
it just exports correctly on 1 project and does not export on other :(
