### ISSUE TITLE
AdMob not initialized, check your configuration.

### ISSUE THREAD

**Issue by dzosek** [Poing-Studios/godot-admob-ios#19]
It doesn't work on my phone

**Comment by gumaciel** [comment]
Hello, what phone are you using? Did you follow the video tutorial?

**Comment by dzosek** [comment]
xiaomi mi a2 lite,yes i follow.
When I click the "is_initialized()" button in the godot editor it returns false or should it?

**Comment by gumaciel** [comment]
But you are testing with the iOS plugin? Or you created the issue on the wrong repository?

No, it should initialize, try to switch to wifi or mobile data

**Comment by dzosek** [comment]
Not everything tests on android and windows. And I wrote in the wrong repository.

**Comment by gumaciel** [comment]
Closing this issue since was opened on wrong repository

https://github.com/Poing-Studios/godot-admob-android/issues/113
