### ISSUE TITLE
No ad to show iOS

### ISSUE THREAD

**Issue by AidenForrest** [Poing-Studios/godot-admob-ios#2]
**Describe the bug**

I have recently released a mobile game on iOS and I was getting an error saying no ad to show before I released it and now it is released I am still getting this error. The intersticial ad unit was created on admob months ago and I have other apps with working adverts that have been out for a while now so my admob account is not new. Why am I still getting this error? Is it an admob problem?

Thanks

**Steps to reproduce**
Godot 3.2.3 iOS release app interstitial ad

**Comment by gumaciel** [comment]
Hi, have you added your app to the AdMob website?

**Comment by gumaciel** [comment]
Did you tested with Unit IDS test? 

If works, then I think you are missing to add the app to AdMob website by linking with the App Store.

Please note: Only publishing your game to App Store won't make the ads appear, to appear you need to add the game on AdMob website.

**Comment by AidenForrest** [comment]
Hi I have not linked my app to admob yet as it has not shown. I'll link it when it shows and hopefully that works.

Thanks very much

**Comment by gumaciel** [comment]
To list on Apple App Store faster, open a conversation here: https://groups.google.com/g/google-admob-ads-sdk/

Like this one: https://groups.google.com/g/google-admob-ads-sdk/c/iFqpp5WOTI0

**Comment by AidenForrest** [comment]
It worked, thank you for all your help.
