### ISSUE TITLE
Error when building: "There is no XCFramework found at..."

### ISSUE THREAD

**Issue by toninkush** [Poing-Studios/godot-admob-ios#20]
Hello. I got a weird error when trying to build in XCode. The errors say that there is no xcframework found at ios/plugins/admobs but all the xcframework files are in there. How do I solve this issue?

**Comment by gumaciel** [comment]
Hi, the path should be `res://ios/plugins/admob/lib`, check if you put the correct path

**Comment by toninkush** [comment]
The path was correct. This particular issue was solved after I manually drag to link them from the same path.

**Comment by gumaciel** [comment]
Nice, but i will investigate this, this shouldn't need to be done to fix, thank you for the reply
