### ISSUE TITLE
[BUG] iPhone 13 behaves differently than other iPhones when it comes to Banner in Notch

### ISSUE THREAD

**Issue by gumaciel** [Poing-Studios/godot-admob-ios#22]
**Describe the bug**
iPhone 13 behaves differently than other iPhones when it comes to Banner in Notch

**Comment by anisc** [comment]
It looks like this behaviour exist in all the iPhone with the notch when upgraded to  15.5
When I upgraded my iphone 11 I got the same bug

**Comment by gumaciel** [comment]
Hi @anisc as i'm testing the notch is normally on Simulator, can you check again and send screenshots of your bug?

iPhone 13 iOS 15.5
![Captura de Tela 2022-06-23 às 22 57 52](https://user-images.githubusercontent.com/20030153/175447007-ea527387-11ca-47aa-a98e-ed84de777d52.png)

iPhone 12 Mini iOS 14.2
![Captura de Tela 2022-06-23 às 22 59 53](https://user-images.githubusercontent.com/20030153/175447206-592ecc49-ddc0-4696-a78f-1dd18bf57d96.png)

iPhone 12 Mini iOS 15.5
![Captura de Tela 2022-06-23 às 23 05 56](https://user-images.githubusercontent.com/20030153/175447774-7229def4-45ab-4290-9d54-3ebe2e1b2f10.png)
