### ISSUE TITLE
[BUG] Can't run on an iOS simulator with an m1 macbook

### ISSUE THREAD

**Issue by bdoucette** [Poing-Studios/godot-admob-ios#26]
**Describe the bug**
Following the youtube guide I get the following error when trying to run my game in the simulator

Undefined symbols for architecture x86_64:
  "Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&)", referenced from:
      ___34-[Interstitial load_interstitial:]_block_invoke in admob.a(Interstitial.o)
      -[Interstitial ad:didFailToPresentFullScreenContentWithError:] in admob.a(Interstitial.o)
      -[Interstitial adDidPresentFullScreenContent:] in admob.a(Interstitial.o)
      -[Interstitial adDidDismissFullScreenContent:] in admob.a(Interstitial.o)
      ___26-[Rewarded load_rewarded:]_block_invoke in admob.a(Rewarded.o)
      -[Rewarded show_rewarded] in admob.a(Rewarded.o)
      ___25-[Rewarded show_rewarded]_block_invoke in admob.a(Rewarded.o)
      ...
     (maybe you meant: Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&))
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**To Reproduce**
1. Export for iOS
2. Modify Build Settings to be Standard Architectures & exclude arm64 + i386
3. Select simulator and press run

**Expected behavior**
The game to build and run in the simulator

**Additional context**
using a macbook pro m1 and the latest version of xcode

Note - when I follow the same steps without the Admob plugin the game can be played on the simulator just fine

**Comment by bdoucette** [comment]
I sorted this one out

I was on 3.5 RC8 so I needed to build the plugin myself for this version

**Comment by gumaciel** [comment]
@bdoucette Hi! I recommend you to use 3.5 stable version.

Here is the version builded for iOS: https://github.com/Poing-Studios/godot-admob-ios/releases/download/v2.1.0/ios-template-v3.5.zip
