### ISSUE TITLE
iOS real ads not shown [BUG]

### ISSUE THREAD

**Issue by AbdulkarimTaha** [Poing-Studios/godot-admob-ios#3]
Hi there
i fallowed the tutorial  for adding iOS admob on iOS that you made , and my ads unit made long time ago like 2 weeks and my app in the Appstore for a week now and it show a test ads not a real ads , if it not show ads i think it maybe because that there is no ads to show yet  but that not the case , its show ads and its test ads . i talked to admob and they say "the ad unit Id's are not our test ad unit Id's. Please note that we can only support integrating the Mobile Ads SDK into apps natively in Android, iOS, Flutter and Unity. I can only suggest you receive support for your issue from the your plugin's issue tracker. I can only guess that some configuration is still holding the test Id's in your app and is overwriting your personal ad unit Id's." 

Godot version 3.3.2

and i use the latest admob version i found on the admob assets 

![Screen Shot 2021-07-14 at 8 05 43 AM](https://user-images.githubusercontent.com/68149815/125565013-cc6d8b5b-e6a7-46e6-9905-af7e3f785633.png)

**Comment by gumaciel** [comment]
Hi! @AbdulkarimTaha , sorry about that, please try to read this tutorial: #2 ,

Have you done this?

https://github.com/Poing-Studios/godot-admob-editor#usage

On `Export -> Resources -> Filters to export non-resources...`, you need to put this: `res://addons/admob/*.json`

**Comment by AbdulkarimTaha** [comment]
hi @gumaciel , i dont know if this is the solution but what i did and its work :
i go to file called variable.gd and i changed ads id and changed is real to true in the config : Dictionary 
and now its showing real ads

**Comment by gumaciel** [comment]
Hi, did you put `res://addons/admob/*.json` on Export?

**Comment by AbdulkarimTaha** [comment]
@gumaciel  no , I didn't see that in the tutorial , i miss it  . should i put it ? even if ads show ?

**Comment by gumaciel** [comment]
Yes, you should put it

Sorry for not being on video tutorial, th video was done with an old version, I will redo the video soon
