### ISSUE TITLE
Build failure in Xcode with Admob plugin enabled (Mac OSx Ventura)

### ISSUE THREAD

**Issue by pedropps2** [Poing-Studios/godot-admob-ios#35]
### Godot version

3.5.1

### Plugin version

v 2.1.1

### Phone information

iPhone 14 pro

### Issue description

Xcode fails build with admob plugin enabled when exporting from code. Xcode build succeeds when I disable admob plugin when exporting from Godot. 

This started failing when I updated Mac OSX to Ventura. The previous week before upgrading, builds worked successfully with the plugin enabled. 

### Steps to reproduce

1. On a Mac running Ventura, Running Godot, and Admob plugins installed for iOS (and Android).
2. Export to iOS
3. Open in Xcode after export
4. Try to build the project
5. Error message is "Undefined symbol: Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&)"

**Comment by pedropps2** [comment]
I was able to resolve this by re-downloding the iOS files and copying them into their respective locations. Sorry for the false alarm.

**Comment by gumaciel** [comment]
hi @Roachdaripper sorry i didn't understand the question
