### ISSUE TITLE
[FEATURE] Add support to build on Xcode

### ISSUE THREAD

**Issue by gumaciel** [Poing-Studios/godot-admob-ios#37]
Currently the build is only working on Terminal, we need to change some settings on Xcode project to the build work properly

**Comment by gumaciel** [comment]
Closing since it's working, but to generate the builds it should be done on Terminal to generate the binaries with the proper arch

**Comment by Roachdaripper** [comment]
can you post the terminal command you used please?

**Comment by gumaciel** [comment]
all the commands are here:

https://github.com/Poing-Studios/godot-admob-ios/blob/5a44b32c004cb8356a0424f47e468f1e27b1b16e/scripts/generate_static_library.sh

like: scons target=release_debug arch=arm64 plugin=admob version=4.0

if you are asking about the Xcode commands, there's not any command, i just use the normal build on Xcode
