### ISSUE TITLE
Banner doesn't load when TOP is unchecked

### ISSUE THREAD

**Issue by ZooHairDev** [Poing-Studios/godot-admob-ios#43]
### Godot version

3.4

### Plugin version

v2.0.0

### Phone information

Android

### Issue description

When I uncheck banner on TOP the banner won't load anymore.
I tried to solve the problem myself but to no avail.

### Steps to reproduce

Go to Admob settings -> Banner -> uncheck on TOP

**Comment by gumaciel** [comment]
Solved on: https://github.com/Poing-Studios/godot-admob-ios/releases/tag/v2.1.0

But please try to use the latest version: https://github.com/Poing-Studios/godot-admob-ios/releases/tag/v2.1.2

**Comment by gumaciel** [comment]
hi @ZooHairDev any updates?

**Comment by gumaciel** [comment]
Closing due stale
