### ISSUE TITLE
Create GodotDictionaryToObject class

### ISSUE THREAD

**Issue by gumaciel** [Poing-Studios/godot-admob-ios#47]
Methods:

- [x] convertDictionaryToGADAdSize
- [x] convertDictionaryToGADRequest
- [x] convertDictionaryToNSDictionary
- [x] convertDictionaryToGADServerSideVerificationOptions
- [x] convertDictionaryToUMPRequestParameters
- [x] convertDictionaryToUMPDebugSettings

**Comment by Mohamed-Kr** [comment]
I also tried doing these classes in the past but actually these two functions exist : [inst_to_dict](https://docs.godotengine.org/en/stable/classes/class_@gdscript.html#class-gdscript-method-inst-to-dict) and [dict_to_inst](https://docs.godotengine.org/en/stable/classes/class_@gdscript.html#class-gdscript-method-dict-to-inst)
Thanks a lot for your work

**Comment by gumaciel** [comment]
Thank you @Mohamed-Kr, I will give a look

**Comment by gumaciel** [comment]
@Mohamed-Kr , your suggestion can't be used in the iOS plugin, but can be used on Godot plugin when sending or receiving the data from iOS or Android plugins. Thank you!
