### ISSUE TITLE
4.0.3 template with 4.1.1

### ISSUE THREAD

**Issue by ahoffman1** [Poing-Studios/godot-admob-ios#51]
### Godot version

4.1.1

### Plugin version

v2.1.2

### Phone information

iPhone 13

### Issue description

After exporting the project, XCode refuses to build and throws the error:
Undefined symbol: ClassDB::bind_methodfi(unsigned int, MethodBind*, MethodDefinition const&, Variant const**, int)
![error](https://github.com/Poing-Studios/godot-admob-ios/assets/1356757/5d288dcd-4cae-418c-9bca-fe08169bfdfe)

Does the plugin just need to be updated? If so, when will the 4.1.1 version be released?

### Steps to reproduce

1. Try to use the 4.0.3 version with 4.1.1 Godot

**Comment by gumaciel** [comment]
Hi @ahoffman1 try to export the game without our plugin to see if the error still happens

**Comment by ahoffman1** [comment]
It exports and runs correctly with the AdMob plugin disabled

**Comment by ahoffman1** [comment]
Hi again,
Any update on this issue?
Thanks

**Comment by gumaciel** [comment]
Hi @ahoffman1 , in this weekend I will try to generate a build to you test, or you can try to build your own

**Comment by ahoffman1** [comment]
If you could build it this weekend that would be great, thank you!

**Comment by gumaciel** [comment]
@ahoffman1 please test it: https://github.com/Poing-Studios/godot-admob-ios/releases/download/v2.1.2/ios-template-v4.1.1.zip

it is attached on: https://github.com/Poing-Studios/godot-admob-ios/releases/tag/v2.1.2

and generated by this action job: https://github.com/Poing-Studios/godot-admob-ios/actions/runs/5708052942/job/15465342464

**Comment by ahoffman1** [comment]
@gumaciel  exporting with AdMob disabled successfully exports, but with it enabled I get this now:
<img width="705" alt="Screenshot_2023-07-30_at_3 04 58_PM" src="https://github.com/Poing-Studios/godot-admob-ios/assets/1356757/c605711e-14e3-4c8e-9095-90e8c432e9d9">

**Comment by gumaciel** [comment]
try to export in another folder and re-download everything again

**Comment by ahoffman1** [comment]
It works, thank you! It exports and launches fine. One issue -- how can I add the test devices via the plugin? Like this: https://developers.google.com/admob/ios/test-ads#add_your_test_device_programmatically
It's requiring a test device identifier to show test ads

**Comment by gumaciel** [comment]
currently it's not possible but if you mark "is_real" to false on Editor, it should set the test device identifier into the phone that is running

on the refactoring which i'm doing you will be able to do it and a lot other things, please wait: #45

**Comment by gumaciel** [comment]
closing the issue since it works for you
