### ISSUE TITLE
I am getting an error when i export 

### ISSUE THREAD

**Issue by javrocks** [Poing-Studios/godot-admob-ios#67]
### Godot version

3.5

### Plugin version

v2.1.1

### Phone information

iPhone 12 IOS ver 16.6

### Issue description

I'm Using Godot ver 3.5, IOS- template ver 3.5, and googlemobileadssdkios ver 9.11.0
I've also tried googlemobileadssdkios ver 10.1 and ver 10.9 but i always get this error below: 

### Steps to reproduce

no steps 

### Additional context

![Error](https://github.com/Poing-Studios/godot-admob-ios/assets/143153420/262d3acb-2aac-4db1-842a-3c74c893e5fe)

**Comment by gumaciel** [comment]
Hi @javrocks try to export in a new folder, outside the folder of the project

**Comment by javrocks** [comment]
> Hi @javrocks try to export in a new folder, outside the folder of the project



> I do that already. I export to a brand new folder called IOS_Export, but the error's still there

**Comment by gumaciel** [comment]
Are you on Windows or MacOS? 

I will verify this bug

**Comment by javrocks** [comment]
I using Windows 11

**Comment by di-kang** [comment]
Would this be related?
I'm having trouble exporting to ios as well.
On Mac, Godot v3.5.2, plugin v2.1.0, googlemobileadssdkios v10.9

<img width="698" alt="Screenshot 2023-08-26 at 00 21 31" src="https://github.com/Poing-Studios/godot-admob-ios/assets/27397353/2c5f4c1d-74e2-4849-a378-a2b4c7c75ff7">

**Comment by gumaciel** [comment]
Test with this version: https://github.com/Poing-Studios/godot-admob-ios/releases/tag/v2.1.2

Can you try to export on MacOS? Because even if you export it on Windows you won't be able to deploy your application because it needs Xcode

But you can export it without the GoogleMobileAdsSDK and then add it on Xcode:

Do these steps:
- ![image](https://github.com/Poing-Studios/godot-admob-ios/assets/20030153/d947a8d6-45e7-4ec3-b0e8-87fef52af59a)
On Linked remove all 
- On Xcode add all `.xcframework` on 
(this is a example image) 
https://tanaschita.com/20210417-how-to-add-local-swift-package-to-ios-project/
![image](https://github.com/Poing-Studios/godot-admob-ios/assets/20030153/f12c53a7-97c2-40cb-b212-8de484184f98)

**Comment by javrocks** [comment]
I use Xcode via an emulator, i don't have a mac. I usually export the whole project and then build it onto my Phone. The error is currently preventing me from exporting a project that Xcode can read. I can however export the project to Xcode without the plugin altogether, but removing the sdk isn't enough to get it to Xcode for me.

**Comment by javrocks** [comment]
Actually i made a mistake when following the instructions, i can export it to Xcode without sdk

**Comment by javrocks** [comment]
I tried adding the .xcframework files but it doesn't load any adds

**Comment by gumaciel** [comment]
@javrocks @di-kang 

I've successfully been able to export the project with AdMob Plugin enabled:

![image](https://github.com/Poing-Studios/godot-admob-ios/assets/20030153/fc8a7908-7390-43c3-8c6a-ee5a1ff55355)


Please create an empty project on Godot 3.5.2, get the latest version of the plugin for 3.x and test again: https://github.com/Poing-Studios/godot-admob-plugin/releases/tag/v1.3.4

**Comment by gumaciel** [comment]
> Would this be related? I'm having trouble exporting to iOS as well. On Mac, Godot v3.5.2, plugin v2.1.0, 

@di-kang please test exporting without the AdMob plugin.

Also, try to create an empty project on Godot 3.5.2, get the latest version of the plugin for 3.x, and test again: https://github.com/Poing-Studios/godot-admob-plugin/releases/tag/v1.3.4

**Comment by javrocks** [comment]
I don't have the Manifest ID for Godot ver 3.5.2
I don't see it listed here....  https://steamdb.info/app/404790/history/

**Comment by javrocks** [comment]
@gumaciel 

Which IOS- template and sdk version are you using ?

**Comment by di-kang** [comment]
@gumaciel thanks🙂
i tried both without the plug-in and with a new empty project right after i got the error. and it works fine. 

however it seems like googlemobileadssdkios was the culprit. maybe i should have done a more thorough research about this issue. after i replaced googlemobileadssdkios with v10.1, export to ios works fine. 

thanks again anyways.

**Comment by gumaciel** [comment]
@javrocks Download here: https://downloads.tuxfamily.org/godotengine/3.5.2/ or https://github.com/godotengine/godot/releases/tag/3.5.2-stable

iOS template version: https://github.com/Poing-Studios/godot-admob-ios/releases/tag/v2.1.2
SDK: https://github.com/Poing-Studios/godot-admob-ios/releases/download/v2.1.2/googlemobileadssdkios.zip (10.1)

---

@di-kang 

If the googlemobileadssdkios is corrupted there's nothing we can do, but as you say the latest version is working, so there's not a problem, using the latest version should work. Thank you for using our plugin!

**Comment by gumaciel** [comment]
@javrocks @di-kang do you guys still have this problem?

**Comment by javrocks** [comment]
Nah not anymore
