### ISSUE TITLE
[FEATURE] Ability to choose whether or not the game should pause in the background while ad is shown

### ISSUE THREAD

**Issue by ZhangWei-bi** [Poing-Studios/godot-admob-ios#70]
**Is your feature request related to a problem? Please describe.**
On iOS, I want the game to continue in the background when ads are shown. For example, in a multiplayer game, when showing an interstitial ad or reward ad, it's causing a disconnection because the game is unresponsive during this time.

**Describe the solution you'd like**
We could have an api that lets you choose if you want the ads to pause the game or not when ads are showing. Seems like admob for Unity has an api for it: https://developers.google.com/admob/unity/reference/class/google-mobile-ads/api/mobile-ads#setiosapppauseonbackground

**Describe alternatives you've considered**
I'm not to sure of other alternatives.

**Additional context**
I'm also using v2.1.2, hopefully that's not an issue.

**Comment by gumaciel** [comment]
Hi @ZhangWei-bi this feature can be added, but only on v3.0.0 because v2 won't receive any updates anymore. You will need to upgrade your plugin to do that

**Comment by ZhangWei-bi** [comment]
@gumaciel Sounds good, I will upgrade to v3.0.0 for the mean time. I’m looking forward to this feature!

**Comment by ZhangWei-bi** [comment]
@gumaciel Any recommendation I can do in the meantime?

**Comment by gumaciel** [comment]
Hi, until this weekend we will rollout an update with this feature

**Comment by gumaciel** [comment]
@ZhangWei-bi Done at:

https://github.com/Poing-Studios/godot-admob-ios/releases/tag/v3.1.0
https://github.com/Poing-Studios/godot-admob-plugin/releases/tag/v3.1.0

please test it

**Comment by ZhangWei-bi** [comment]
@gumaciel Thank you so much! I haven't had the chance to upgrade to v3. I am on Godot 4.0.4, will this work or do I need to upgrade to 4.1? I don't mind recompiling if I need to.

**Comment by gumaciel** [comment]
Hi @ZhangWei-bi this feature is only for v3, which only supports Godot 4.1+ 😞 

Can you try to upgrade your Godot to 4.1? Using the v3 will be more easier to use and have more features.

**Comment by gumaciel** [comment]
@ZhangWei-bi docs for usage: https://poing-studios.github.io/godot-admob-plugin/ios_pause_background/

**Comment by ZhangWei-bi** [comment]
@gumaciel Finally had the time to upgrade my project to 4.2.1 and this feature works great, thank you!!
