### ISSUE TITLE
Create/keep a guide/documentation for setting up older versions

### ISSUE THREAD

**Issue by davekaa** [Poing-Studios/godot-admob-ios#82]
**Is your feature request related to a problem? Please describe.**
I'm using Godot v3.5.1 (at the time of writing Godot 4.2 is already out). Therefor I need to use godot-admob-ios v2.1.4, but I have no idea how to set this up since there is no documentation for it. The only documentation I could find is about the Godot plugin for iOS of AdMob, which is great, but it's for Godot v4.1+.

**Describe the solution you'd like**
Create and keep a guide or documentation for older versions so that these can still be used.

**Describe alternatives you've considered**
I had 2 options:
- Update my Godot project to Godot v4.1+, which is way too much work at this point of the project.
- Find and use something else to make AdMob work somehow.

**Comment by gumaciel** [comment]
Hi, there's already some documentation of these versions, soon I will send them to you

**Comment by gumaciel** [comment]
@davekaa the documentation that we have are these READMEs:

v1 (Godot 3): https://github.com/Poing-Studios/godot-admob-plugin/blob/v1/README.md
v2 (Godot 4+): https://github.com/Poing-Studios/godot-admob-plugin/blob/v2/README.md
v3 (current): https://github.com/Poing-Studios/godot-admob-plugin/blob/master/README.md

We also have this video showing how can use the v1 or v2: https://youtu.be/ZnlH3INcAGs
And this for v3: https://youtu.be/WpVGn7ZasKM
